import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  defineNuxtModule,
  addImportsDir,
  addTypeTemplate,
  addTemplate,
  createResolver,
} from "@nuxt/kit";

/** A single variant entry as it appears in either the base registry or appConfig overrides. */
interface VariantEntry {
  extends?: string | string[];
  [key: string]: unknown;
}

export interface ModuleOptions {
  registry: Record<string, unknown>;
  configKey: string;
}

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: "nuxt-variants",
    configKey: "variants",
  },
  defaults: {
    registry: {},
    configKey: "variants",
  },
  setup(options, nuxt) {
    const resolver = createResolver(import.meta.url);

    Object.assign(nuxt.options.runtimeConfig.public, {
      variantRegistry: options.registry,
      variantsConfigKey: options.configKey,
    });

    addTypeTemplate({
      filename: "types/nuxt-variants.d.ts",
      getContents: () => `// Generated by nuxt-variants
// Augment CustomVariantRegistry in your project to enable typed variant resolution
export interface CustomVariantRegistry {}
`,
    });

    nuxt.options.alias["#nuxt-variants"] = `${nuxt.options.buildDir}/types/nuxt-variants`;

    const baseRegistry = (options.registry ?? {}) as Record<string, VariantEntry>;
    const appRegistry = (nuxt.options.appConfig[options.configKey] ?? {}) as Record<
      string,
      VariantEntry
    >;

    const allKeys = new Set([...Object.keys(baseRegistry), ...Object.keys(appRegistry)]);
    const variantGraph: Record<string, string[]> = {};

    for (const key of allKeys) {
      const extendsValue = appRegistry[key]?.extends ?? baseRegistry[key]?.extends;
      variantGraph[key] =
        extendsValue === undefined
          ? []
          : Array.isArray(extendsValue)
            ? extendsValue
            : [extendsValue];
    }

    const graphMjsPath = join(nuxt.options.buildDir, "variants-graph.mjs");
    const graphDmtsPath = join(nuxt.options.buildDir, "variants-graph.d.mts");
    const graphContent = `export const variantGraph = ${JSON.stringify(variantGraph, null, 2)};\n`;
    const graphDtsContent = `export declare const variantGraph: Record<string, string[]>;\n`;

    // Write eagerly so content.config.ts can import the file at Nuxt init time,
    // before any hooks fire. addTemplate keeps them in sync during build.
    mkdirSync(nuxt.options.buildDir, { recursive: true });
    writeFileSync(graphMjsPath, graphContent, "utf-8");
    writeFileSync(graphDmtsPath, graphDtsContent, "utf-8");

    addTemplate({ filename: "variants-graph.mjs", getContents: () => graphContent });
    addTemplate({ filename: "variants-graph.d.mts", getContents: () => graphDtsContent });

    nuxt.options.alias["#variants-graph"] = graphMjsPath;

    nuxt.hook("prepare:types", ({ references }) => {
      // Re-write in case Nuxt cleaned buildDir after setup() ran.
      writeFileSync(graphMjsPath, graphContent, "utf-8");
      writeFileSync(graphDmtsPath, graphDtsContent, "utf-8");
      references.push({ path: graphDmtsPath });
    });

    addImportsDir(resolver.resolve("./runtime/composables"));
    addImportsDir(resolver.resolve("./runtime/utils"));
  },
});
